package com.smart.access.control.constants;

public class ReplyCode {
    public static final String PASSWORD_MATCH = "10";
    public static final String PASSWORD_WRONG = "11";
    public static final String SYSTEM_BUSY_PASSWORD = "00";
    public static final String OXFF = "FF";
    public static final String OX00 = "00";
    public static final String OX10 = "10";
    public static final String OX11 = "11";
    public static final String OPERATION_NOT_ALLOWED = "06";
    public static final String USER_REGISTRATION_SUCCESSFUL = "13";
    public static final String USER_REGISTRATION_FAILED = "14";
    public static final String USER_ALREADY_EXIST = "15";
    public static final String USER_REGISTRATION_IN_PROCESS = "16";
    public static final String REMOVE_FINGER = "17";
    public static final String PLACE_FINGER = "18";
    public static final String PLACE_SAME_FINGER_AGAIN = "19";
    public static final String USER_REGISTRATION_TIMEOUT = "1A";
    public static final String USER_FINGER_IMAGE_TOO_NOISY = "1B";
    public static final String USER_FINGER_SENSOR_ISSUE = "1C";
    public static final String USER_FINGER_NOT_PLACED_PROPERLY = "1D";
    public static final String USER_DELETION_SUCCESSFUL = "20";
    public static final String USER_DELETION_FAILED = "21";
    public static final String USER_NOT_EXIST = "22";
    public static final String USER_DETAILS_WITH_USERID = "25";
    public static final String INVALID_USERID = "26";
    public static final String USER_DETAILS_SHARING_IN_PROGRESS = "29";
    public static final String USER_DETAILS_SHARING_COMPLETE = "2A";
    public static final String DELETE_ALL_USER_SUCCESSFUL = "2D";
    public static final String DELETE_ALL_USER_DECLINE = "3D";
    public static final String OX30 = "30";
    public static final String OX31 = "31";
    public static final String OX32 = "32";
    public static final String OX33 = "33";
    public static final String OX34 = "34";
    public static final String OX35 = "35";
    public static final String OX36 = "36";
    public static final String OX37 = "37";
    public static final String OX38 = "38";
    public static final String OX39 = "39";
    public static final String OX40 = "40";
    public static final String OX41 = "41";
    public static final String OX42 = "42";
    public static final String OX43 = "43";
    public static final String OX44 = "44";
    public static final String OX45 = "45";
    public static final String OX46 = "46";
    public static final String OX47 = "47";
    public static final String OX48 = "48";
    public static final String OX49 = "49";
    public static final String OX3A = "3A";
    public static final String OX3B = "3B";
}

